FROM alpine:3.14
RUN apk update && apk upgrade \
    && apk add --no-cache bash \
    && apk update --no-cache curl; 
WORKDIR /cabal-binary
COPY cardano-datum-keeper-exe /cabal-binary/
EXPOSE 8082
CMD ["/cabal-binary/cardano-datum-keeper-exe"]