name:                cardano-explorer-backend
version:             0.1.0.0
github:              "ergolabs/cardano-explorer-backend"
license:             BSD3
author:              "ergolabs"
maintainer:          "ergolabs"
copyright:           "2021 ergolabs"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Github username here/cardano-explorer-backend#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cardano-explorer-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cardano-explorer-backend

tests:
  cardano-explorer-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cardano-explorer-backend
